### ISSUE TITLE
layout bug

### ISSUE THREAD

**Issue by daxingplay** [chimeric/dokuwiki-plugin-metaheaders#1]
after i installed this plugin, i add $headers['meta'][] = array( 'name' => 'DC.title', 'content' => 'yourdomain.org', 'cond' => '^blog:*' ); in the config file, but then i found there was a margin in the top of every page. what's wrong?

**Comment by chimeric** [comment]
Which editor did you use? It has to be utf-8 compatible and not write a BOM at the end of the config file.

BTW, I corrected the example (on the wiki as well), it was missing a dot:

$headers['meta'][] = array( 'name' => 'DC.title', 'content' => 'yourdomain.org', 'cond' => '^blog:.*' );
